version: '3.0'
services:
  sync:
    build:
       context: ./research-hub-sync
       args:
           - http_proxy
           - https_proxy
    environment: 
      - CONTENTFUL_SPACE_ID=${CONTENTFUL_SPACE_ID}
      - CONTENTFUL_ACCESS_TOKEN=${CONTENTFUL_ACCESS_TOKEN}
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}

